version: '3'
services:

  train_system:
    image: mariadb:11.0
    container_name: train_system
    environment:
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: train_system
    ports:
      - '3306:3306'